/**
 * Prism.js language definition for zschema
 * zSchema.*.zolo - Data schema definition files
 *
 * Extends base 'zolo' language with file-type-specific patterns.
 *
 * Generated by zlsp/zlsp/generators/generate_prism_zolo.py
 * DO NOT EDIT MANUALLY - regenerate with: python3 -m zlsp.generators.generate_prism_zolo
 */

Prism.languages.zschema = Prism.languages.extend('zolo', {
    'zschema-zmeta-root': {
        pattern: /((?:^|\n)[ \t]*)zMeta(?=\s*:)/m,
        alias: 'function',
        lookbehind: true,
    },
    'root-key': {
        pattern: /((?:^|\n)[ \t]*)[A-Z][a-zA-Z0-9_]*(?=\s*(?:\([^)]+\))?[*!^~]?:)/m,
        alias: 'class-name',
        lookbehind: true,
    },
    'zschema-zos-data': {
        pattern: /(?<=\n)[ \t]{1}(?:Data_Type|Data_Label|Data_Source|zUIVersion|zMigration|zMigrationVersion|Schema_Name|zUITracking|Data_Path)(?=\s*:)/m,
        alias: 'keyword',
        lookbehind: true,
    },
    'zschema-property': {
        pattern: /(?<=\n)[ \t]{2,}(?:rules|constraints|indexes|required|max_length|validator|primary_key|pattern_message|pk|check|min_length|zConstraints|minlength|auto_increment|backfill|immutable|version|unique|transform|foreign_key|format|maxlength|max|enum|on_delete|default|error_message|min|pattern|nullable|max_size|renamed_from|zHash|comment|blob_input|type|fk)(?=\s*:)/m,
        alias: 'keyword',
        lookbehind: true,
    },
    'property': {
        pattern: /\b[a-zA-Z][a-zA-Z0-9_]*(?=\s*(?:\([^)]+\))?[*!]?:)/,
    }
});

// Support both ```zschema and ```zSchema code fences
Prism.languages.zSchema = Prism.languages.zschema;
