"""
Integration tests for Prism.js pattern generation.

Tests the complete generation pipeline for all 6 languages.
"""

import subprocess
import pytest
from pathlib import Path


@pytest.fixture
def project_root():
    """Get project root directory."""
    return Path(__file__).parent.parent.parent.parent


@pytest.fixture
def generated_dir(project_root):
    """Get generated files directory."""
    return project_root / 'zlsp' / 'generated'


@pytest.fixture
def bifrost_syntax_dir(project_root):
    """Get bifrost syntax directory."""
    return project_root / 'zOS' / 'bifrost' / 'src' / 'syntax'


@pytest.fixture
def static_js_dir(project_root):
    """Get zCloud static JS directory (where /static/ is served from)."""
    return project_root / 'zCloud' / 'static' / 'js'


class TestGenerationPipeline:
    """Test the complete generation pipeline."""
    
    def test_generator_runs_successfully(self, project_root):
        """Test that generator script runs without errors."""
        result = subprocess.run(
            ['python3', '-m', 'zlsp.generators.generate_prism_zolo'],
            cwd=project_root,
            capture_output=True,
            text=True
        )
        
        assert result.returncode == 0, f"Generator failed:\n{result.stderr}"
        assert 'Generation complete!' in result.stdout
    
    def test_all_languages_generated(self, generated_dir):
        """Test that all 6 language files are generated."""
        expected_files = [
            'prism-zolo.js',
            'prism-zspark.js',
            'prism-zui.js',
            'prism-zschema.js',
            'prism-zconfig.js',
            'prism-zenv.js',
        ]
        
        for filename in expected_files:
            path = generated_dir / filename
            assert path.exists(), f"{filename} not generated in {generated_dir}"
            assert path.stat().st_size > 0, f"{filename} is empty"
    
    def test_all_languages_copied_to_bifrost_syntax(self, bifrost_syntax_dir):
        """Test that all 6 language files are copied to bifrost syntax directory."""
        expected_files = [
            'prism-zolo.js',
            'prism-zspark.js',
            'prism-zui.js',
            'prism-zschema.js',
            'prism-zconfig.js',
            'prism-zenv.js',
        ]
        
        for filename in expected_files:
            path = bifrost_syntax_dir / filename
            assert path.exists(), f"{filename} not copied to {bifrost_syntax_dir}"
            assert path.stat().st_size > 0, f"{filename} in bifrost syntax is empty"
    
    def test_all_languages_copied_to_static_js(self, static_js_dir):
        """Test that all 6 language files are copied to zCloud static JS directory."""
        expected_files = [
            'prism-zolo.js',
            'prism-zspark.js',
            'prism-zui.js',
            'prism-zschema.js',
            'prism-zconfig.js',
            'prism-zenv.js',
        ]
        
        for filename in expected_files:
            path = static_js_dir / filename
            assert path.exists(), f"{filename} not copied to {static_js_dir}"
            assert path.stat().st_size > 0, f"{filename} in zCloud static is empty"


class TestGeneratedFileContent:
    """Test the content of generated files."""
    
    @pytest.fixture(params=[
        'zolo', 'zspark', 'zui', 'zschema', 'zconfig', 'zenv'
    ])
    def language_name(self, request):
        return request.param
    
    @pytest.fixture
    def language_file(self, generated_dir, language_name):
        return generated_dir / f'prism-{language_name}.js'
    
    def test_file_has_prism_definition(self, language_file, language_name):
        """Test that file defines Prism.languages correctly."""
        content = language_file.read_text()
        assert f'Prism.languages.{language_name}' in content
    
    def test_file_has_header_comment(self, language_file):
        """Test that file has generation header."""
        content = language_file.read_text()
        assert '/**' in content
        assert 'Generated by zlsp/zlsp/generators/generate_prism_zolo.py' in content
        assert 'DO NOT EDIT MANUALLY' in content
    
    def test_file_has_comment_pattern(self, language_file):
        """Test that all files have comment pattern (in base or inherited)."""
        content = language_file.read_text()
        
        # Check if this is base zolo or extended language
        is_base = 'Prism.languages.zolo = {' in content
        is_extended = "Prism.languages.extend('zolo'," in content
        
        if is_base:
            # Base zolo should have comment pattern explicitly
            assert "'comment':" in content or '"comment":' in content
            assert '#' in content  # Comment pattern includes #
        elif is_extended:
            # Extended languages inherit comment from base zolo
            assert "Prism.languages.extend('zolo'," in content
        else:
            pytest.fail("File doesn't match base or extended pattern structure")
    
    def test_file_has_punctuation_pattern(self, language_file):
        """Test that all files have punctuation pattern (in base or inherited)."""
        content = language_file.read_text()
        
        # Check if this is base zolo or extended language
        is_base = 'Prism.languages.zolo = {' in content
        is_extended = "Prism.languages.extend('zolo'," in content
        
        if is_base:
            # Base zolo should have punctuation pattern explicitly
            assert "'punctuation':" in content or '"punctuation":' in content
        elif is_extended:
            # Extended languages inherit punctuation from base zolo
            assert "Prism.languages.extend('zolo'," in content
        else:
            pytest.fail("File doesn't match base or extended pattern structure")
    
    def test_file_ends_with_closing_brace(self, language_file):
        """Test that file ends properly (either `};` for base or `});` for extended)."""
        content = language_file.read_text()
        
        # Check if this is base zolo or extended language
        is_base = 'Prism.languages.zolo = {' in content
        is_extended = "Prism.languages.extend('zolo'," in content
        
        if is_base:
            assert content.strip().endswith('};'), "Base language should end with '};'"
        elif is_extended:
            assert content.strip().endswith('});'), "Extended language should end with '});'"
        else:
            pytest.fail("File doesn't match base or extended pattern structure")
    
    def test_file_has_no_syntax_errors(self, language_file):
        """Test basic JavaScript syntax validity."""
        content = language_file.read_text()
        
        # Check file ends with proper closing (either `};` for base or `});` for extended)
        is_base = 'Prism.languages.zolo = {' in content
        is_extended = "Prism.languages.extend('zolo'," in content
        
        if is_base:
            assert content.strip().endswith('};'), "Base language should end with '}'"
        elif is_extended:
            assert content.strip().endswith('});'), "Extended language should end with '})'"
        
        # Check braces are balanced
        open_braces = content.count('{')
        close_braces = content.count('}')
        assert open_braces == close_braces, "Unbalanced braces"
        
        # Check brackets are balanced
        open_brackets = content.count('[')
        close_brackets = content.count(']')
        assert open_brackets == close_brackets, "Unbalanced brackets"
        
        # Note: We don't check parentheses balance because regex patterns
        # include non-capturing groups (?:, lookaheads (?=, etc. that make
        # simple counting inaccurate


class TestLanguageSpecificPatterns:
    """Test language-specific patterns in generated files."""
    
    def test_zolo_has_root_key_pattern(self, generated_dir):
        """Test generic zolo has root-key pattern."""
        content = (generated_dir / 'prism-zolo.js').read_text()
        assert "'root-key':" in content or '"root-key":' in content
        assert 'class-name' in content  # Root keys should be class-name alias
    
    def test_zspark_has_zspark_root_pattern(self, generated_dir):
        """Test zspark has zspark-root pattern."""
        content = (generated_dir / 'prism-zspark.js').read_text()
        assert "'zspark-root':" in content or '"zspark-root":' in content
        assert 'zSpark' in content  # Pattern should match zSpark
    
    def test_zspark_has_nested_pattern(self, generated_dir):
        """Test zspark has nested key pattern."""
        content = (generated_dir / 'prism-zspark.js').read_text()
        assert "'zspark-nested':" in content or '"zspark-nested":' in content
    
    def test_zui_has_special_root_pattern(self, generated_dir):
        """Test zui has special root patterns."""
        content = (generated_dir / 'prism-zui.js').read_text()
        assert "'zui-special-root':" in content or '"zui-special-root":' in content
        assert 'zMeta' in content or 'zVaF' in content
    
    def test_zui_has_element_pattern(self, generated_dir):
        """Test zui has UI element patterns."""
        content = (generated_dir / 'prism-zui.js').read_text()
        assert "'zui-element':" in content or '"zui-element":' in content
    
    def test_zui_has_element_property_pattern(self, generated_dir):
        """Test zui has UI element property patterns."""
        content = (generated_dir / 'prism-zui.js').read_text()
        assert "'zui-element-property':" in content or '"zui-element-property":' in content
    
    def test_zschema_has_zmeta_root_pattern(self, generated_dir):
        """Test zschema has zMeta root pattern."""
        content = (generated_dir / 'prism-zschema.js').read_text()
        assert "'zschema-zmeta-root':" in content or '"zschema-zmeta-root":' in content
        assert 'zMeta' in content
    
    def test_zschema_has_property_pattern(self, generated_dir):
        """Test zschema has field property patterns."""
        content = (generated_dir / 'prism-zschema.js').read_text()
        assert "'zschema-property':" in content or '"zschema-property":' in content
    
    def test_zconfig_has_special_root_pattern(self, generated_dir):
        """Test zconfig has special root patterns."""
        content = (generated_dir / 'prism-zconfig.js').read_text()
        assert "'zconfig-special-root':" in content or '"zconfig-special-root":' in content
        assert 'zMachine' in content
    
    def test_zconfig_has_section_patterns(self, generated_dir):
        """Test zconfig has section header patterns."""
        content = (generated_dir / 'prism-zconfig.js').read_text()
        assert "'zmachine-locked-section':" in content or '"zmachine-locked-section":' in content
        assert "'zmachine-editable-section':" in content or '"zmachine-editable-section":' in content
    
    def test_zenv_has_config_root_pattern(self, generated_dir):
        """Test zenv has config root patterns."""
        content = (generated_dir / 'prism-zenv.js').read_text()
        assert "'zenv-config-root':" in content or '"zenv-config-root":' in content
    
    def test_zenv_has_znavbar_pattern(self, generated_dir):
        """Test zenv has ZNAVBAR nested patterns."""
        content = (generated_dir / 'prism-zenv.js').read_text()
        assert "'znavbar-nested':" in content or '"znavbar-nested":' in content
    
    def test_zenv_has_zpath_pattern(self, generated_dir):
        """Test zenv has zPath value patterns."""
        content = (generated_dir / 'prism-zenv.js').read_text()
        assert "'zpath-value':" in content or '"zpath-value":' in content


class TestFileSynchronization:
    """Test that generated files are properly synchronized."""
    
    @pytest.fixture(params=[
        'zolo', 'zspark', 'zui', 'zschema', 'zconfig', 'zenv'
    ])
    def language_name(self, request):
        return request.param
    
    def test_generated_and_deployed_files_match(
        self, generated_dir, bifrost_syntax_dir, static_js_dir, language_name
    ):
        """Test that generated and deployed files have identical content."""
        generated_file = generated_dir / f'prism-{language_name}.js'
        bifrost_syntax_file = bifrost_syntax_dir / f'prism-{language_name}.js'
        static_js_file = static_js_dir / f'prism-{language_name}.js'
        
        generated_content = generated_file.read_text()
        bifrost_syntax_content = bifrost_syntax_file.read_text()
        static_js_content = static_js_file.read_text()
        
        assert generated_content == bifrost_syntax_content, \
            f"prism-{language_name}.js differs between generated/ and bifrost/syntax/"
        assert generated_content == static_js_content, \
            f"prism-{language_name}.js differs between generated/ and zCloud/static/js/"


class TestPatternOrdering:
    """Test that patterns are in correct order."""
    
    @pytest.fixture(params=[
        'zolo', 'zspark', 'zui', 'zschema', 'zconfig', 'zenv'
    ])
    def language_file(self, generated_dir, request):
        language_name = request.param
        return generated_dir / f'prism-{language_name}.js'
    
    def test_comment_comes_first(self, language_file):
        """Test that comment pattern comes first (in base or inherited)."""
        content = language_file.read_text()

        # Check if this is base zolo or extended language
        is_base = 'Prism.languages.zolo = {' in content
        is_extended = "Prism.languages.extend('zolo'," in content

        if is_base:
            # Base zolo should have comment explicitly first
            comment_pos = content.find("'comment':")
            if comment_pos == -1:
                comment_pos = content.find('"comment":')
            
            lang_def_pos = content.find('Prism.languages.')
            assert comment_pos > lang_def_pos, "Comment should be first pattern in base"
        elif is_extended:
            # Extended languages inherit comment from base zolo
            # Just verify it extends properly
            assert "Prism.languages.extend('zolo'," in content
        else:
            pytest.fail("File doesn't match base or extended pattern structure")
    
    def test_punctuation_comes_last(self, language_file):
        """Test that punctuation pattern comes last (in base or inherited)."""
        content = language_file.read_text()

        # Check if this is base zolo or extended language
        is_base = 'Prism.languages.zolo = {' in content
        is_extended = "Prism.languages.extend('zolo'," in content

        if is_base:
            # Base zolo should have punctuation explicitly last
            punct_pos = content.find("'punctuation':")
            if punct_pos == -1:
                punct_pos = content.find('"punctuation":')
            
            closing_pos = content.rfind('};')
            
            # Punctuation should be near the end (before closing brace)
            assert punct_pos < closing_pos, "Punctuation should be last pattern in base"
            assert closing_pos - punct_pos < 200, "Punctuation should be close to end"
        elif is_extended:
            # Extended languages inherit punctuation from base zolo
            # Just verify it extends properly
            assert "Prism.languages.extend('zolo'," in content
        else:
            pytest.fail("File doesn't match base or extended pattern structure")


class TestRegression:
    """Regression tests for specific bugs."""
    
    def test_settings_page_bug_fixed(self, generated_dir):
        """
        Regression test: Settings_Page should be colored as root-key.
        
        This was the original bug that started the generator project.
        """
        content = (generated_dir / 'prism-zolo.js').read_text()
        
        # Check that root-key pattern exists
        assert "'root-key':" in content or '"root-key":' in content
        
        # Check that it matches any case (lowercase or Capital)
        assert '[a-zA-Z]' in content
        
        # Check that it has column 0 detection (capturing or non-capturing group)
        assert ('(^|' in content or '(?:^|' in content or '(?<=\\n)' in content), \
            "Root key pattern must match at column 0"
