"""
Prism.js CSS theme generator - Converts canonical theme to Prism.js CSS.

NOTE: This generator ONLY produces CSS for colors/styling.
Prism.js pattern definitions (JS) are generated by zlsp/generators/generate_prism_zolo.py

Architecture:
- Patterns (JS): Parser SSOT → zlsp/generators/generate_prism_zolo.py
- Colors (CSS): Theme YAML → zlsp/themes/generators/prism.py (this file)

Generates:
1. prism-zolo-theme.css (CSS theme with colors from zlsp theme YAML)
"""
from datetime import datetime
from pathlib import Path
from typing import Dict, Any
from . import BaseGenerator
from .. import Theme


class PrismCSSGenerator(BaseGenerator):
    """
    Generates Prism.js CSS theme from zlsp color theme.
    
    IMPORTANT: This does NOT generate JS pattern definitions.
    For Prism.js language patterns, use: zlsp/generators/generate_prism_zolo.py
    """
    
    def _get_editor_name(self) -> str:
        return 'prism'
    
    def generate(self) -> str:
        """
        Generate Prism.js CSS theme.
        
        Returns:
            String containing the complete CSS theme file
        """
        return self._generate_css_theme()
    
    def _DEPRECATED_generate_prism_language(self) -> str:
        """
        DEPRECATED: JS pattern generation moved to zlsp/generators/generate_prism_zolo.py
        
        This method is kept for reference but should NOT be used.
        Use the SSOT-based generator instead:
            python3 -m zlsp.generators.generate_prism_zolo
        
        OLD approach (WRONG):
        - Hardcoded patterns in Python strings
        - No file-type specialization (zspark, zui, etc.)
        - Duplicates parser logic
        
        NEW approach (CORRECT):
        - Patterns extracted from parser SSOT (KeyDetector, TokenRegistry)
        - 6 language-specific files (zolo, zspark, zui, zschema, zconfig, zenv)
        - Automatic sync with parser changes
        """
        raise DeprecationWarning(
            "JS pattern generation moved to zlsp/generators/generate_prism_zolo.py. "
            "Use: python3 -m zlsp.generators.generate_prism_zolo"
        )
        
        # OLD HARDCODED PATTERNS (DEPRECATED - DO NOT USE)
        return '''(function (Prism) {
    /**
     * Zolo Language Definition
     * Declarative configuration syntax with dual-mode rendering (Terminal + GUI)
     * 
     * String-First Philosophy:
     * Most values are unquoted strings. Pattern order matters:
     * 1. Comments (highest priority)
     * 2. Special keys (zMeta, zRBAC) at root
     * 3. Root keys (unindented capitals - zBlocks)
     * 4. Metadata keys (_zClass, _zId)
     * 5. Display events (zH1, zText, zMD)
     * 6. Property keys (nested, including zNavBar under zMeta)
     * 7. Unquoted string values (BEFORE standalone booleans/numbers)
     * 8. Standalone booleans, numbers (only when alone after colon)
     * 
     * CRITICAL: This is a standalone language definition.
     * Do NOT inherit from YAML, JSON, or any other language.
     * Prism's default patterns must NOT apply to .zolo files.
     */
    
    // Define zolo as a completely new language (no inheritance)
    Prism.languages.zolo = {
        // ═══════════════════════════════════════════════════════════
        // COMMENTS (Highest Priority)
        // ═══════════════════════════════════════════════════════════
        'comment': {
            pattern: /#.*/,
            greedy: true
        },
        
        // ═══════════════════════════════════════════════════════════
        // SPECIAL KEYS (zMeta, zVaF, zRBAC) - Must be at root (no indent)
        // ═══════════════════════════════════════════════════════════
        // From SSOT: zlsp/parser/zvaf/key_detector.py line 69
        'special-key': {
            pattern: /^(?:zMeta|zVaF|zRBAC)(?=\\s*[*]?:)/mg,
            alias: 'builtin',
        },
        
        // ═══════════════════════════════════════════════════════════
        // ROOT-LEVEL KEYS (zBlocks) - Salmon orange
        // ═══════════════════════════════════════════════════════════
        // Pattern: ^[A-Za-z][a-zA-Z0-9_]*: (NO leading whitespace)
        // Examples: Page_Header:, zFundamentals_Details:, zBlock1:
        // Excludes: zMeta, zVaF, zRBAC (special keys handled above)
        'root-key': {
            pattern: /^(?!zMeta|zVaF|zRBAC)[A-Za-z][a-zA-Z0-9_]*(?=\\s*(?:\\([^)]+\\))?[*!^~]?:)/mg,
            alias: 'class-name',
        },
        
        // ═══════════════════════════════════════════════════════════
        // METADATA KEYS (_zClass, _zId, _zStyle) - Cyan
        // ═══════════════════════════════════════════════════════════
        'metadata': {
            pattern: /\\b_z[A-Z][a-zA-Z]+(?=:)/g,
            alias: 'keyword',
        },
        
        // ═══════════════════════════════════════════════════════════
        // DISPLAY EVENT KEYS (zH1, zText, zMD, zTable, zUL)
        // ═══════════════════════════════════════════════════════════
        // Pattern: Indented z[A-Z] keys (UI elements)
        // Examples: zH1:, zText:, zMD:, zTable:, zUL:
        // Excludes: zMeta, zRBAC (handled by special-key)
        // Note: zNavBar will be caught by property pattern instead
        'display-event': {
            pattern: /(?:^\\s+)z(?:H[1-6]|Text|MD|Table|UL|OL|DL|Image|URL|Crumbs|Input|Checkbox|Btn|Button|Select|Range|Terminal|Wizard)(?=\\s*(?:\\([^)]+\\))?[*!]?:)/gm,
            alias: 'function',
        },
        
        // ═══════════════════════════════════════════════════════════
        // UI ELEMENT PROPERTIES - Lavender (Inside zH1, zText, zTable, etc.)
        // ═══════════════════════════════════════════════════════════
        // From SSOT: token_registry.py UI_ELEMENT_PROPERTY_KEYS
        // Examples: label:, color:, content:, title:, columns:, rows:
        'ui-property': {
            pattern: /(?:^\\s+)(?:src|alt_text|caption|color|open_prompt|indent|label|style|semantic|href|target|rel|window|content|pause|break_message|format|items|title|columns|rows|limit|offset|show_header|interactive|show|parent|prompt|type|placeholder|required|disabled|readonly|min|max|step|pattern|autocomplete|value|checked|name|id|maxlength|minlength|multiple|size|options|multi|prefix|suffix|action)(?=\\s*(?:\\([^)]+\\))?[*!]?:)/gm,
            alias: 'variable',
        },
        
        // ═══════════════════════════════════════════════════════════
        // PROPERTY KEYS (Other nested keys) - Golden yellow
        // ═══════════════════════════════════════════════════════════
        // Pattern: Indented identifiers before :
        // Examples: Header:, Options:, zNavBar: (when indented under zMeta)
        // This catches ALL indented keys not matched above
        'property': {
            pattern: /(?:^\\s+)[a-zA-Z][a-zA-Z0-9_]*(?=\\s*(?:\\([^)]+\\))?[*!]?:)/gm,
        },
        
        // ═══════════════════════════════════════════════════════════
        // TYPE HINTS - Lavender
        // ═══════════════════════════════════════════════════════════
        'type': {
            pattern: /\\([^)]+\\)/g,
            alias: 'type',
        },
        
        // ═══════════════════════════════════════════════════════════
        // MODIFIERS (*, !, ^, ~)
        // ═══════════════════════════════════════════════════════════
        'modifier': {
            pattern: /[*!^~](?=:)/,
            alias: 'operator',
        },
        
        // ═══════════════════════════════════════════════════════════
        // QUOTED STRINGS - Light cream (Process FIRST)
        // ═══════════════════════════════════════════════════════════
        'string': {
            pattern: /"(?:\\\\.|[^\\\\"])*"|'(?:\\\\.|[^\\\\'])*'/,
            greedy: true
        },
        
        // ═══════════════════════════════════════════════════════════
        // STANDALONE BOOLEANS - Blue (After colon, only if alone)
        // ═══════════════════════════════════════════════════════════
        'boolean': {
            pattern: /:\\s+(?:true|false|True|False|yes|no|on|off)(?=\\s*(?:#|$))/g,
            inside: {
                'punctuation': /^:/,
                'boolean': /(?:true|false|True|False|yes|no|on|off)/
            }
        },
        
        // ═══════════════════════════════════════════════════════════
        // STANDALONE NUMBERS - Dark orange (After colon, only if alone)
        // ═══════════════════════════════════════════════════════════
        'number-value': {
            pattern: /:\\s+-?\\d+(?:\\.\\d+)?(?=\\s*(?:#|$))/g,
            inside: {
                'punctuation': /^:/,
                'number': /-?\\d+(?:\\.\\d+)?/
            }
        },
        
        // ═══════════════════════════════════════════════════════════
        // UNQUOTED STRING VALUES - Light cream (Everything else)
        // ═══════════════════════════════════════════════════════════
        // Matches compound values like "zContainer zmt-5 zmb-2"
        // Must come AFTER boolean/number to avoid conflicts
        'unquoted-value': {
            pattern: /:\\s+[^#\\n]+/g,
            inside: {
                'punctuation': /^:/,
                'string': /[^:\\s].*/
            }
        },
        
        // ═══════════════════════════════════════════════════════════
        // PUNCTUATION (colons not in values) - Soft yellow
        // ═══════════════════════════════════════════════════════════
        'punctuation': /:/,
        
        // ═══════════════════════════════════════════════════════════
        // ESCAPE SEQUENCES (Inside strings)
        // ═══════════════════════════════════════════════════════════
        'escape-sequence': {
            pattern: /\\\\[uU][0-9A-Fa-f]{4,8}|\\\\[nrtbf\\\\"']/,
            alias: 'string',
            inside: {
                'escape': /\\\\[uU]|\\\\[nrtbf\\\\"']/
            }
        }
    };
    
    // Register aliases for CSS styling
    Prism.languages.zolo['root-key'].alias = 'class-name';
    Prism.languages.zolo['display-event'].alias = 'function';
    Prism.languages.zolo['metadata'].alias = 'keyword';
    Prism.languages.zolo['special-key'].alias = 'builtin';
    
    // Prevent Prism from applying default language patterns
    // Mark as a complete, standalone language definition
    Prism.languages.zolo.rest = Prism.languages.zolo;
    
}(Prism));
'''  # END DEPRECATED HARDCODED PATTERNS
    
    def _generate_css_theme(self) -> str:
        """
        Generate Prism.js CSS theme from zlsp theme colors (SSOT).
        
        Maps zlsp token types to Prism CSS classes and generates
        color rules based on the canonical theme palette.
        
        Generates both:
        1. Old .language-zolo rules (backward compatibility)
        2. Language-specific rules (.language-zspark, .language-zui, etc.)
        3. Generic .token.* fallback rules
        
        Returns:
            String containing the complete CSS theme file
        """
        # Map Prism token classes to zlsp token types (SSOT) for OLD language-zolo
        token_mapping = {
            'special-key': 'zmetaKey',           # light_green (#87d787) - zMeta, zVaF, zRBAC
            'builtin': 'zmetaKey',               # light_green
            'root-key': 'rootKey',               # salmon_orange (#ffaf87) - zBlocks
            'class-name': 'rootKey',             # salmon_orange
            'metadata': 'bifrostKey',            # dark_cyan (#00ffff) - _zClass, _zId
            'keyword': 'bifrostKey',             # dark_cyan
            'zdispatch-event': 'dispatchKey',    # golden_yellow (#ffd787) - zDialog, zData, zCRUD
            'dispatch-event': 'dispatchKey',     # golden_yellow
            'display-event': 'uiElementKey',     # orange_red (#ff5f00) - zH1, zText, zMD
            'function': 'uiElementKey',          # orange_red
            'ui-property': 'uiElementPropertyKey', # lavender (#af87ff) - label, color, content
            'variable': 'uiElementPropertyKey',  # lavender
            'property': 'nestedKey',             # golden_yellow (#ffd787) - other nested keys
            'string': 'string',                  # light_cream (#fffbcb) - all string values
            'unquoted-value': 'string',          # light_cream (#fffbcb) - unquoted string values
            'boolean': 'boolean',                # deep_blue (#0087ff) - true, false
            'number': 'number',                  # dark_orange (#FF8C00) - 123, 3.14
            'number-value': 'number',            # dark_orange (#FF8C00) - standalone numbers
            'null': 'null',                      # deep_blue (#0087ff) - null, None
            'comment': 'comment',                # gray (#6F6F62) - # comments
            'type': 'typeHint',                  # lavender (#af87ff) - (int), (str)
            'escape-sequence': 'escapeSequence', # bright_orange (#ff0000) - \n, \t, \uXXXX
            'punctuation': 'colon',              # soft_yellow (#ffff5f) - colons
            'modifier': 'colon',                 # soft_yellow
            'operator': 'colon',                 # soft_yellow
        }
        
        css = f'''/**
 * Prism.js CSS Theme for .zolo syntax highlighting
 * 
 * AUTO-GENERATED by zlsp/themes/generators/prism.py
 * DO NOT EDIT MANUALLY - Changes will be overwritten!
 * 
 * Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
 * Source: zlsp/themes/zolo_default.yaml (SSOT)
 * Maintainer: Run from zlsp to regenerate
 * 
 * Colors are derived from the canonical zlsp theme to ensure
 * consistency between IDE and web syntax highlighting.
 */

'''
        
        # Generate CSS rules for each token type
        for prism_class, token_type in token_mapping.items():
            style = self.theme.get_token_style(token_type)
            if not style:
                continue
            
            hex_color = style.get('hex')
            if not hex_color:
                continue
            
            description = style.get('description', '')
            style_attr = style.get('style', 'none')
            
            # Generate comment
            css += f'/* {description} */\n'
            # zSpark uses base zolo styles (pure alias)
            css += f'.language-zolo .token.{prism_class},\n'
            css += f'.language-zspark .token.{prism_class} {{\n'
            css += f'  color: {hex_color} !important;\n'
            
            # Add font-weight for root keys
            if prism_class in ['root-key', 'class-name']:
                css += f'  font-weight: 600;\n'
            elif prism_class in ['display-event', 'function']:
                css += f'  font-weight: 500;\n'
            
            # Add font-style for italics
            if style_attr == 'italic' or prism_class in ['comment', 'type']:
                css += f'  font-style: italic;\n'
            
            css += f'}}\n\n'
        
        # Add multi-language specific rules
        css += self._generate_multi_language_css()
        
        return css
    
    def _generate_multi_language_css(self) -> str:
        """
        Generate language-specific CSS rules for zspark, zui, zenv, etc.
        
        These override the generic .token.* rules for specific language contexts.
        """
        css = '''/* ============================================================================
 * Multi-Language Support (zspark, zui, zschema, zconfig, zenv)
 * Language-specific token styling from zlsp SSOT
 * ============================================================================ */

'''
        
        # zUI-specific rules
        css += '''/* zUI-specific tokens (from SSOT: semantic-colors.json) */
.language-zui .token.function {
  /* zui-element: zH1, zText, zURL → uiElementKey */
  color: ''' + self.theme.get_token_style('uiElementKey').get('hex', '#ff5f00') + ''' !important;
  font-weight: 500;
}

.language-zui .token.variable {
  /* zui-element-property: label, color, href → uiElementPropertyKey */
  color: ''' + self.theme.get_token_style('uiElementPropertyKey').get('hex', '#af87ff') + ''' !important;
}

.language-zui .token.keyword {
  /* metadata: _zClass, _zId → bifrostKey */
  color: ''' + self.theme.get_token_style('bifrostKey').get('hex', '#00ffff') + ''' !important;
}

.language-zui .token.class-name {
  /* root-key: Main_Page, Getting_Started → rootKey */
  color: ''' + self.theme.get_token_style('rootKey').get('hex', '#ffaf87') + ''' !important;
  font-weight: 600;
}

.language-zui .token.property {
  /* Nested keys like Header, Actions → nestedKey */
  color: ''' + self.theme.get_token_style('nestedKey').get('hex', '#ffd787') + ''' !important;
}

.language-zui .token.constant {
  /* zRBAC key → zrbacKey */
  color: ''' + self.theme.get_token_style('zrbacKey').get('hex', '#ff0000') + ''' !important;
  font-weight: 600;
}

'''
        
        # zEnv-specific rules
        css += '''/* zEnv-specific tokens */
.language-zenv .token.constant {
  /* zRBAC key in zEnv files → zrbacKey */
  color: ''' + self.theme.get_token_style('zrbacKey').get('hex', '#ff0000') + ''' !important;
  font-weight: 600;
}

.language-zenv .token.variable {
  /* Prefix modifiers (^, ~) in zEnv → zrbacOptionKey */
  color: ''' + self.theme.get_token_style('zrbacOptionKey').get('hex', '#af87ff') + ''' !important;
}

'''
        
        # zSpark-specific rules
        # DISABLED: zSpark being rebuilt from scratch - uses base zolo styles
        css += '''/* zSpark uses base zolo styles (no overrides) */

'''
        
        # Generic fallback rules (apply to all languages unless overridden)
        css += '''/* Generic multi-language aliases (fallback for all languages) */
.token.function {
  color: ''' + self.theme.get_token_style('uiElementKey').get('hex', '#87d787') + ''' !important;
  font-weight: 600;
}

.token.class-name {
  color: ''' + self.theme.get_token_style('rootKey').get('hex', '#ffaf87') + ''' !important;
  font-weight: 600;
}

/* SSOT: Type hints split into TWO tokens (value_emitters.py:352-362) */
.token.type-hint {
  /* Container for type hint - inherits from nested tokens */
  color: ''' + self.theme.get_token_style('typeHint').get('hex', '#00ffff') + ''' !important;
}

.token.type-hint-paren {
  /* SSOT: TokenType.TYPE_HINT_PAREN → typeHintParen → lavender */
  color: ''' + self.theme.get_token_style('typeHintParen').get('hex', '#af87ff') + ''' !important;
}

.token.type-hint-text {
  /* SSOT: TokenType.TYPE_HINT → typeHint → dark_cyan */
  color: ''' + self.theme.get_token_style('typeHint').get('hex', '#00ffff') + ''' !important;
  font-style: italic;
}

/* Legacy support: OLD .token.type selector (before nested tokenization) */
.token.type {
  color: ''' + self.theme.get_token_style('typeHint').get('hex', '#00ffff') + ''' !important;
  font-style: italic;
}

.token.boolean {
  color: ''' + self.theme.get_token_style('boolean').get('hex', '#0087ff') + ''' !important;
}

.token.number {
  color: ''' + self.theme.get_token_style('number').get('hex', '#FF8C00') + ''' !important;
}

.token.string {
  color: ''' + self.theme.get_token_style('string').get('hex', '#fffbcb') + ''' !important;
}

.token.punctuation {
  color: ''' + self.theme.get_token_style('colon').get('hex', '#ffff5f') + ''' !important;
}

.token.operator {
  color: ''' + self.theme.get_token_style('colon').get('hex', '#ffff5f') + ''' !important;
}

/* Structural brackets and braces (from Prism.js patterns) */
.token.bracket,
.language-zolo .token.bracket {
  color: ''' + self.theme.get_token_style('bracketStructural').get('hex', '#ff00ff') + ''' !important;
}

.token.brace,
.language-zolo .token.brace {
  color: ''' + self.theme.get_token_style('braceStructural').get('hex', '#d700ff') + ''' !important;
}

'''
        
        return css
    
    def generate_css(self) -> str:
        """
        Generate Prism.js CSS theme from zlsp theme colors.
        
        Returns:
            String containing the complete CSS theme file
        """
        return self._generate_css_theme()
    
    def generate_css_to_file(self, css_output_path: Path = None) -> Path:
        """
        Generate and write Prism.js CSS theme to file.
        
        NOTE: This only generates CSS. For JS patterns, use:
            python3 -m zlsp.generators.generate_prism_zolo
        
        Args:
            css_output_path: Optional custom output path for CSS.
                            Defaults to zCloud/static/css/prism-zolo-theme.css
        
        Returns:
            Path to generated CSS file
        """
        if css_output_path is None:
            zlsp_root = Path(__file__).parent.parent.parent.parent
            project_root = zlsp_root.parent
            css_output_path = project_root / 'zCloud' / 'static' / 'css' / 'prism-zolo-theme.css'
        
        # Ensure directory exists
        css_output_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Generate and write CSS
        css_content = self.generate_css()
        css_output_path.write_text(css_content, encoding='utf-8')
        
        # Also copy to zTheme/src/css/ (npm package source)
        zlsp_root = Path(__file__).parent.parent.parent.parent
        project_root = zlsp_root.parent
        ztheme_css_path = project_root / 'zOS' / 'zTheme' / 'src' / 'css' / 'prism-zolo-theme.css'
        ztheme_css_path.parent.mkdir(parents=True, exist_ok=True)
        ztheme_css_path.write_text(css_content, encoding='utf-8')
        
        return css_output_path


def generate_prism_css_theme(css_output_path: Path = None) -> Path:
    """
    Standalone function to generate Prism.js CSS theme from zlsp theme colors.
    
    NOTE: This only generates CSS. For JS patterns, use:
        python3 -m zlsp.generators.generate_prism_zolo
    
    Args:
        css_output_path: Optional custom output path for CSS
    
    Returns:
        Path to generated CSS file
    """
    # Use default theme
    from .. import load_theme
    theme = load_theme('zolo_default')
    
    generator = PrismCSSGenerator(theme)
    return generator.generate_css_to_file(css_output_path)


if __name__ == '__main__':
    """CLI entry point for regenerating Prism.js CSS theme"""
    print("=" * 70)
    print("Prism.js CSS Theme Generator")
    print("=" * 70)
    print()
    print("⚠️  NOTE: This generates CSS ONLY (colors from theme)")
    print("   For JS patterns, run: python3 -m zlsp.generators.generate_prism_zolo")
    print()
    print("Source: zlsp/themes/zolo_default.yaml (color theme)")
    print("Output: prism-zolo-theme.css")
    print()
    
    css_file = generate_prism_css_theme()
    css_content = css_file.read_text()
    
    print(f"✅ Generated CSS: {css_file}")
    print(f"   Size: {len(css_content)} bytes")
    print(f"   Lines: {len(css_content.splitlines())}")
    print()
    print("📁 Also copied to:")
    print(f"   - zOS/zTheme/src/css/prism-zolo-theme.css")
    print()
    print("=" * 70)
    print("✅ CSS generation complete!")
    print("=" * 70)
    print()
    print("Next steps:")
    print("  1. Generate JS patterns: python3 -m zlsp.generators.generate_prism_zolo")
    print("  2. Hard refresh browser (Cmd+Shift+R)")
    print("  3. Check syntax highlighting colors match IDE")
    print()
    print("=" * 70)
